# @baseUrl = https://localhost:7165
@baseUrl = https://inventory-api-194340759475.asia-east1.run.app

### 查詢所有商品
GET {{baseUrl}}/api/products

### 查詢單一商品
GET {{baseUrl}}/api/products/7

### 依分類查詢
GET {{baseUrl}}/api/products/category/飲料

### 新增商品
POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "name": "測試商品",
  "price": 100,
  "stock": 50,
  "category": "飲料"
}

### 修改商品（把 id=1 的商品改名改價）
PUT {{baseUrl}}/api/products/99999
Content-Type: application/json

{
  "name": "abc飲品-改名",
  "price": 120,
  "stock": 25,
  "category": "飲料"
}

### 刪除商品
DELETE {{baseUrl}}/api/products/7

### 測試驗證：價格為負數（應該失敗）
POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "name": "測試商品",
  "price": -50,
  "stock": 10,
  "category": "測試"
}

### 測試驗證：名稱為空（應該失敗）
POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "name": "",
  "price": 100,
  "stock": 10,
  "category": "測試"
}
### 新增測試資料到 Cloud SQL
POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "name": "雲端測試商品",
  "price": 99.50,
  "stock": 10,
  "category": "測試"
}

### ===== Token 驗證測試 =====

### 1. 登入取得 Token
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin1234"
}

### 2. 不帶 Token 查詢（應該 401）
GET {{baseUrl}}/api/products

### 3. 帶 Token 查詢（把下面的 Token 換成步驟1拿到的）
GET {{baseUrl}}/api/products
Authorization: Bearer f80242be63924386b86d465eba93e407

### 4. 帶錯誤 Token（應該 401）
GET {{baseUrl}}/api/products
Authorization: Bearer abc123